In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tqdm.notebook import tqdm

from ML2_lib import RV_SGDAve
from ML2_lib import loss

from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
data_boston = load_boston()

In [2]:
x = data_boston.data
# x = x.T
x.shape


(506, 13)

In [3]:
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)

In [4]:
y = data_boston.target.reshape(1,-1)
y = y.T
y.shape

(506, 1)

In [51]:
# データセットを分割する関数の読み込み


# 訓練用データセットとテスト用データセットへの分割
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=0)


w_init = np.zeros(13).reshape(1,-1)

son = loss.LinearQuadraticLoss()

In [58]:
hoge = RV_SGDAve.RVSGDRealData(loss_type=son,c=1 ,lr=0.1)

In [53]:
k=1
hoge.learn_data(k=k,w_init=w_init,x=x_train,y=y_train)


In [54]:
hoge.predict(x_test[1].reshape(1,-1))

-5.323101759168409

In [55]:
y_test[1]

array([50.])

In [57]:
hoge.transition(k,x_test,y_test)

/Users/naoki/.pyenv/versions/3.8.6/envs/ML2/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/naoki/.pyenv/versions/3.8.6/envs/ML2/lib/python3.8/site-packages/numpy/core/_methods.py:180: RuntimeWarning: invalid value encountered in true_divide
  ret = um.true_divide(


[array([273.12637255]),
 array([273.31244862]),
 array([279.58041549]),
 array([283.87481327]),
 array([288.4142535]),
 array([293.22061242]),
 array([297.94615937]),
 array([295.79938664]),
 array([292.83551252]),
 array([291.87454899]),
 array([291.56540176]),
 array([292.93135297]),
 array([294.87143272]),
 array([295.53369781]),
 array([297.14065631]),
 array([297.11450945]),
 array([297.49839814]),
 array([296.33364392]),
 array([295.83056232]),
 array([295.56047661]),
 array([295.56862114]),
 array([296.34409928]),
 array([297.86370932]),
 array([298.88759721]),
 array([299.06825142]),
 array([299.9305769]),
 array([301.05227922]),
 array([302.40180329]),
 array([303.64789417]),
 array([305.13251375]),
 array([306.13395695]),
 array([305.84674178]),
 array([305.98238774]),
 array([306.48386951]),
 array([307.23473792]),
 array([308.21045101]),
 array([308.84597548]),
 array([308.66047152]),
 array([307.86438656]),
 array([308.09740948]),
 array([308.015007]),
 array([308.79893012