In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from ML2_lib import loss
import pickle
from ML2_lib import plot_set
from ML2_lib import RV_SGDAve

from tqdm.notebook import tqdm

In [2]:
d = 2

lr = 0.001

c = 1

n = 200
k_list = [1, 2, 4, 5, 10, 20]


# ノイズの種類（勾配）
noise_type_list = ["lognormal", "normal", "student_t"]

E_var = 1.75
# ノイズの分散（勾配）
def noise_var(noise_type):
    if noise_type == "lognormal":
        return [1.2,1.75,1.9]
    elif noise_type == "normal":
        return [1.5,1.9,2.2]
    elif noise_type == "student_t":
        return [1.5,3,5]
    else:
        raise ValueError("lognormalかnormalかsutdent_tで")


# 検証時に加える関数値にノイズの種類
noise_type_f = "lognormal"
f_E_var = 1.75

noise = "lognormal"

w_init = np.array([2, 2])

# 初期値
w_init_list_0 = [-10, 0, 10]
w_init_list_1 = [-10, 0, 10]

k_string = [f"{i + 1}" for i in k_list]



In [3]:
for noise_type in tqdm(noise_type_list):
    noise_var_list = noise_var(noise_type)
    for E_var in noise_var_list:
        for w_init_0 in w_init_list_0:
            for w_init_1 in w_init_list_1:
                result_to_pickle = {}
                son = loss.RosenBrock(d=d, noise_type=noise_type, E_var=E_var, f_E_var=f_E_var, noise_type_f=noise_type_f)
                RV = RV_SGDAve.RVSGDByW(model_opt=son, c=c, n=n, lr=lr)
                w_init = np.array([w_init_0, w_init_1])
                k_core_list, k_selected_index, k_w_rv = RV.k_all_transition(k_list=k_list, w_init=w_init)
                result_to_pickle["k_core_list"] = k_core_list
                result_to_pickle["k_selected_index"] = k_selected_index
                with open("sample.pickle", mode="wb") as f:
                    pickle.dump(k_core_list, f)
                # plot_set.multiple_w_value_2d_k_candidates_contour(k_list=k_list, k_list_core_store=k_core_list, _t_max=n,
                #                                   k_selected_index=k_selected_index, f=son)






  0%|          | 0/3 [00:00<?, ?it/s]

[[-9.77998906 -9.98899968]]
[[-9.57743082 -9.97857484]]
[[-9.38984505 -9.96865756]]
[[-9.21524849 -9.95919318]]
[[-9.05202838 -9.95013495]]
[[-8.89885555 -9.94144361]]
[[-8.75462098 -9.9330857 ]]
[[-8.61838948 -9.92503258]]
[[-8.48936466 -9.91725917]]
[[-8.3668629  -9.90974355]]
[[-8.25029298 -9.90246654]]
[[-8.13913982 -9.89541083]]
[[-8.03295206 -9.88856143]]
[[-7.93133208 -9.88190444]]
[[-7.83392769 -9.87542757]]
[[-7.74042544 -9.86911976]]
[[-7.65054522 -9.86297099]]
[[-7.56403561 -9.85697208]]
[[-7.48067018 -9.85111466]]
[[-7.40024416 -9.84539111]]
[[-7.32257186 -9.8397944 ]]
[[-7.24748448 -9.83431814]]
[[-7.17482787 -9.82895633]]
[[-7.10446112 -9.82370346]]
[[-7.03625514 -9.81855505]]
[[-6.97009102 -9.81350563]]
[[-6.90585936 -9.80855082]]
[[-6.84345916 -9.80368736]]
[[-6.78279697 -9.79891051]]
[[-6.723786   -9.79421675]]
[[-6.66634583 -9.78960267]]
[[-6.61040162 -9.78506511]]
[[-6.55588371 -9.78060105]]
[[-6.50272696 -9.77620787]]
[[-6.45087071 -9.77188283]]
[[-6.40025791 -9.767

In [4]:
son = loss.RosenBrock(d=d, noise_type=noise_type, E_var=E_var, f_E_var=f_E_var, noise_type_f=noise_type_f)
RV = RV_SGDAve.RVSGDByW(model_opt=son, c=c, n=n, lr=lr)
w_init = np.array([w_init_0, w_init_1])
k_core_list, k_selected_index, k_w_rv = RV.k_all_transition(k_list=k_list, w_init=w_init)
# with open("sample.pickle", mode="wb") as f:
#     pickle.dump(k_core_list, f)

[[ 9.81999129 10.00899952]]
[[ 9.65341451 10.01752688]]
[[ 9.49851139 10.02563256]]
[[ 9.35384987 10.03335827]]
[[ 9.21824528 10.04074015]]
[[ 9.09070705 10.04780891]]
[[ 8.97039845 10.05459085]]
[[ 8.85660558 10.06110942]]
[[ 8.74871431 10.06738495]]
[[ 8.64619294 10.07343533]]
[[ 8.54857764 10.0792763 ]]
[[ 8.4554616  10.08492215]]
[[ 8.36648602 10.09038559]]
[[ 8.28133274 10.09567819]]
[[ 8.19971828 10.10081036]]
[[ 8.12138912 10.10579144]]
[[ 8.04611761 10.11063005]]
[[ 7.97369856 10.11533405]]
[[ 7.90394625 10.11991054]]
[[ 7.83669232 10.12436616]]
[[ 7.77178363 10.128707  ]]
[[ 7.70908022 10.13293861]]
[[ 7.64845392 10.13706625]]
[[ 7.58978746 10.14109469]]
[[ 7.53297252 10.14502839]]
[[ 7.47790979 10.14887163]]
[[ 7.42450735 10.15262825]]
[[ 7.37268007 10.15630189]]
[[ 7.32234912 10.15989609]]
[[ 7.2734413  10.16341393]]
[[ 7.22588852 10.16685837]]
[[ 7.17962724 10.17023226]]
[[ 7.13459819 10.17353829]]
[[ 7.09074602 10.176779  ]]
[[ 7.0480188  10.17995671]]
[[ 7.00636796 10.183

In [5]:
# with open("sample.pickle", mode="rb") as f:
#     d = pickle.load(f)

In [6]:
d

2