In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision.datasets as datasets

from ML2_lib import models
from ML2_lib import SGDByTorch

from tqdm import tqdm_notebook as tqdm

from ML2_lib import format_data
from ML2_lib import RV_SGD_Torch

from sklearn.model_selection import train_test_split

In [2]:
data_transform = transforms.ToTensor()

# 学習データを読み込む DataLoader を作成する。
train_dataset = datasets.FashionMNIST(
    root="./data", train=True, transform=data_transform, download=True
)
train_data_loader = torch.utils.data.DataLoader(
    train_dataset, batch_size=1, shuffle=True
)

# テストデータを読み込む DataLoader を作成する。
test_dataset = datasets.FashionMNIST(
    root="./data", train=False, transform=data_transform, download=True
)
test_data_loader = torch.utils.data.DataLoader(
    test_dataset, batch_size=1, shuffle=True
)



/Users/naoki/.pyenv/versions/3.8.6/envs/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [12]:
model = models.FF_L1(w_num=784,c_num=10,unit_num=512)
X_train, y_train, X_test, y_test = format_data.FashionMNIST_data().return_data()
X_train, X_valid = train_test_split(X_train, test_size=0.1, shuffle=False)
y_train, y_valid = train_test_split(y_train, test_size=0.1, shuffle=False)

/Users/naoki/.pyenv/versions/3.8.6/envs/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:62: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/Users/naoki/.pyenv/versions/3.8.6/envs/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:67: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/Users/naoki/.pyenv/versions/3.8.6/envs/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:52: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
/Users/naoki/.pyenv/versions/3.8.6/envs/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:57: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


In [13]:

hoge = SGDByTorch.SGDTorch(lr=0.01)
hoge.learn(x=X_train,y=y_train, model=model,class_num=10,X_test=X_test,Y_test=y_test)

/Users/naoki/ML/GD/ML2_lib/SGDByTorch.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(X_test).float())


step : 0
[[   5    0    0    1    0    0    0    0   14  980]
 [   0    0    0    1    0    1    0    0    5  993]
 [   3    0    0    0    2    0    0    0    1  994]
 [   0    0    0    1    2    0    0    0    4  993]
 [   4    0    0    0    1    0    0    0    4  991]
 [  53    0    0    5   12    2    0    2   55  871]
 [   2    0    0    2    3    0    0    0   11  982]
 [  16    0    0    3    6    0    0    0   45  930]
 [   2    0    0    1    0    1    0    0    3  993]
 [   0    0    0    0    0    0    0    0    0 1000]]
              precision    recall  f1-score   support

           0       0.06      0.01      0.01      1000
           1       0.00      0.00      0.00      1000
           2       0.00      0.00      0.00      1000
           3       0.07      0.00      0.00      1000
           4       0.04      0.00      0.00      1000
           5       0.50      0.00      0.00      1000
           6       0.00      0.00      0.00      1000
           7       0.00    

/Users/naoki/.pyenv/versions/3.8.6/envs/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/3.8.6/envs/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/3.8.6/envs/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

step : 1000
[[879  15  28  48   3   1   9   1  16   0]
 [ 17 930  14  29   8   0   0   0   2   0]
 [ 29   3 787  12 157   1   4   0   7   0]
 [ 95  39  19 815  22   0   4   0   6   0]
 [  2  21 525  86 355   0   4   0   7   0]
 [  1   0   1   3   0 685   0 187  13 110]
 [315   8 498  27 108   0  22   0  22   0]
 [  0   0   0   0   0 106   0 831   0  63]
 [  4   2  55   9   0  10   5  13 901   1]
 [  2   0   0   1   1  53   0  32   1 910]]
              precision    recall  f1-score   support

           0       0.65      0.88      0.75      1000
           1       0.91      0.93      0.92      1000
           2       0.41      0.79      0.54      1000
           3       0.79      0.81      0.80      1000
           4       0.54      0.35      0.43      1000
           5       0.80      0.69      0.74      1000
           6       0.46      0.02      0.04      1000
           7       0.78      0.83      0.81      1000
           8       0.92      0.90      0.91      1000
           9    

/Users/naoki/ML/GD/ML2_lib/SGDByTorch.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(X_test).float())


step : 2000
[[654  10   8 132   5   2 150   0  39   0]
 [  0 912  12  59  10   0   5   0   2   0]
 [  4   2 535  16 288   1 117   0  37   0]
 [ 13  12   0 886  14   1  65   0   9   0]
 [  0   3 132  84 704   0  52   0  25   0]
 [  1   0   0   3   0 753   0 165  16  62]
 [ 96   2 117  99 297   0 321   0  68   0]
 [  0   0   0   0   0  24   0 916   0  60]
 [  1   2   8  11   2   3  11  10 951   1]
 [  0   0   0   2   0  10   0  91   2 895]]
              precision    recall  f1-score   support

           0       0.85      0.65      0.74      1000
           1       0.97      0.91      0.94      1000
           2       0.66      0.54      0.59      1000
           3       0.69      0.89      0.77      1000
           4       0.53      0.70      0.61      1000
           5       0.95      0.75      0.84      1000
           6       0.45      0.32      0.37      1000
           7       0.77      0.92      0.84      1000
           8       0.83      0.95      0.89      1000
           9    

/Users/naoki/ML/GD/ML2_lib/SGDByTorch.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(X_test).float())


step : 3000
[[781   4   4  45   0   1 144   0  20   1]
 [  3 917   6  40   1   0  31   0   2   0]
 [ 20   0 476   4   7   1 471   0  21   0]
 [ 46   9   0 758   0   1 180   0   5   1]
 [  0   3 149  26  15   0 798   0   9   0]
 [  1   0   0   2   0 800   0  61   9 127]
 [166   2  68  17   2   4 699   0  42   0]
 [  0   0   0   0   0  59   0 840   0 101]
 [  1   1   0   7   0   9  33   5 943   1]
 [  0   0   0   0   0   3   0  43   1 953]]
              precision    recall  f1-score   support

           0       0.77      0.78      0.77      1000
           1       0.98      0.92      0.95      1000
           2       0.68      0.48      0.56      1000
           3       0.84      0.76      0.80      1000
           4       0.60      0.01      0.03      1000
           5       0.91      0.80      0.85      1000
           6       0.30      0.70      0.42      1000
           7       0.89      0.84      0.86      1000
           8       0.90      0.94      0.92      1000
           9    

/Users/naoki/ML/GD/ML2_lib/SGDByTorch.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(X_test).float())


step : 4000
[[721  21   9  59  14   4 141   0  31   0]
 [  0 944   3  33  17   0   1   0   2   0]
 [  7   3 463   7 361   2 125   0  32   0]
 [ 25  26   1 789  95   1  54   0   8   1]
 [  0   6  38  19 901   0  25   0  11   0]
 [  0   0   0   1   0 894   0  36  13  56]
 [130  11  68  26 392   2 319   0  52   0]
 [  0   0   0   0   0  86   0 738   5 171]
 [  0   1   0   7   7   4  16   2 961   2]
 [  0   0   0   0   0  26   0  14   1 959]]
              precision    recall  f1-score   support

           0       0.82      0.72      0.77      1000
           1       0.93      0.94      0.94      1000
           2       0.80      0.46      0.59      1000
           3       0.84      0.79      0.81      1000
           4       0.50      0.90      0.65      1000
           5       0.88      0.89      0.89      1000
           6       0.47      0.32      0.38      1000
           7       0.93      0.74      0.82      1000
           8       0.86      0.96      0.91      1000
           9    

/Users/naoki/ML/GD/ML2_lib/SGDByTorch.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(X_test).float())


step : 5000
[[585  34   8  32   1   5 302   0  33   0]
 [  0 955  11  24   4   0   4   0   2   0]
 [  2   6 637   6 158   2 158   0  31   0]
 [ 12  44   3 761  29   1 137   0  12   1]
 [  0   7 183  33 643   2 111   0  21   0]
 [  0   0   0   1   0 830   0  96   6  67]
 [ 61  14 124  15 111   3 612   0  60   0]
 [  0   0   0   0   0  27   0 887   0  86]
 [  0   1   5   3   2   7  13   5 963   1]
 [  0   0   0   0   0   8   0  47   1 944]]
              precision    recall  f1-score   support

           0       0.89      0.58      0.70      1000
           1       0.90      0.95      0.93      1000
           2       0.66      0.64      0.65      1000
           3       0.87      0.76      0.81      1000
           4       0.68      0.64      0.66      1000
           5       0.94      0.83      0.88      1000
           6       0.46      0.61      0.52      1000
           7       0.86      0.89      0.87      1000
           8       0.85      0.96      0.90      1000
           9    

/Users/naoki/ML/GD/ML2_lib/SGDByTorch.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(X_test).float())


step : 6000
[[911   3  18   9   5   1  16   0  36   1]
 [ 25 935  11  20   7   0   0   0   2   0]
 [ 26   1 664   4 236   1  19   0  49   0]
 [194  10  17 672  53   1  40   0  13   0]
 [  8   1  84  15 842   0  24   0  26   0]
 [  1   0   0   2   0 851   0  75  11  60]
 [316   2 172   9 228   0 192   0  81   0]
 [  0   0   0   0   0  29   0 927   0  44]
 [  5   1   4   2   4   3   4   4 972   1]
 [  0   0   0   0   0   4   0  69   2 925]]
              precision    recall  f1-score   support

           0       0.61      0.91      0.73      1000
           1       0.98      0.94      0.96      1000
           2       0.68      0.66      0.67      1000
           3       0.92      0.67      0.78      1000
           4       0.61      0.84      0.71      1000
           5       0.96      0.85      0.90      1000
           6       0.65      0.19      0.30      1000
           7       0.86      0.93      0.89      1000
           8       0.82      0.97      0.89      1000
           9    

/Users/naoki/ML/GD/ML2_lib/SGDByTorch.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(X_test).float())


step : 7000
[[594   4   9  39   4   1 331   0  17   1]
 [  0 938   9  26  10   0  15   0   2   0]
 [  3   1 476   3 296   1 208   0  12   0]
 [ 16   6   2 726  37   1 208   0   3   1]
 [  0   1  36  10 753   0 195   0   5   0]
 [  1   0   0   1   0 780   0  80   8 130]
 [ 63   2  70  21 125   1 688   0  30   0]
 [  0   0   0   0   0  17   0 869   0 114]
 [  0   1   5   3   3   2  35   5 945   1]
 [  0   0   0   0   0   1   0  35   1 963]]
              precision    recall  f1-score   support

           0       0.88      0.59      0.71      1000
           1       0.98      0.94      0.96      1000
           2       0.78      0.48      0.59      1000
           3       0.88      0.73      0.79      1000
           4       0.61      0.75      0.68      1000
           5       0.97      0.78      0.86      1000
           6       0.41      0.69      0.51      1000
           7       0.88      0.87      0.87      1000
           8       0.92      0.94      0.93      1000
           9    

/Users/naoki/ML/GD/ML2_lib/SGDByTorch.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(X_test).float())


KeyboardInterrupt: 

In [5]:
train_dataset.data.shape[0]

60000