In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from ML2_lib import models
from ML2_lib import GDByTorch
import torch.nn.functional as F
import torch
from sklearn.preprocessing import LabelBinarizer
from ML2_lib import format_data

In [4]:
name_path = "data/adult/adult_classification.names"
train_path = "data/adult/adult_classification.csv"
test_path = "data/adult/adult_classification.test"
hoge = format_data.Format(train_path=train_path,name_path=name_path,test_path=test_path)


X_train, y_train, X_test, y_test = hoge.data_return()

In [6]:
w_dim = X_train.shape[1]
class_num = int(max(y_train) + 1)
unit_num = 2
model = models.FF_L1(w_num=w_dim,c_num=class_num,unit_num=unit_num)

In [7]:
hoge = GDByTorch.GDTorch(lr=1000)

In [8]:
sgd_model, loss_stack, test_loss_stack,accuracy_stack = hoge.learn(x=X_train, y=y_train, model=model,class_num=class_num,X_test=X_test,Y_test=y_test)

step : 0
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+02, -

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 1000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+02

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 2000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+02

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 3000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+02

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 4000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+02

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 5000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+02

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 6000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+02

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 7000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+02

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 8000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+02

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 9000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+02

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 10000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 11000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 12000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 13000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 14000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 15000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 16000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 17000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 18000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 19000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 20000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 21000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 22000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 23000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 24000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 25000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 26000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 27000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 28000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 29000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


step : 30000
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
OrderedDict([('fc1.weight', tensor([[-8.4809e+02, -3.5748e+02, -1.7413e+03,  3.3578e+00, -3.1731e+01,
         -1.1863e+03, -3.3011e+01, -1.9336e+02, -2.4921e+03, -5.1021e+01,
         -1.8696e+02, -1.0212e+02,  7.8143e-01, -8.6226e+01, -1.0653e+02,
         -3.4243e+01, -1.8713e+01, -3.9024e+01, -6.3832e+01, -6.1462e+01,
         -4.9710e+01, -1.6767e+02, -3.6507e+02, -3.8870e+00, -1.2987e+03,
         -6.8591e+01, -3.9754e+00, -1.0578e+01, -6.7866e+02, -4.6933e+02,
         -1.2667e+00, -1.3367e+03, -3.3611e+01, -9.9219e+02, -1.1420e+02,
         -1.1223e+02, -4.7256e+02,  3.9036e+00, -2.2894e+0

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


TypeError: cannot unpack non-iterable FF_L1 object

In [ ]:

fig = plt.figure(figsize=(10.0, 8.0))
ax1 = fig.add_subplot(111)

ax1.set_title("train data NLL Loss")

ax1.plot(loss_stack)
ax1.set_xlabel("step")
plt.show()

In [ ]:
fig = plt.figure(figsize=(10.0, 8.0))
ax1 = fig.add_subplot(111)
ax1.set_title("test data NLL Loss")

ax1.plot(test_loss_stack)
ax1.set_xlabel("step")
plt.show()

In [ ]:
fig = plt.figure(figsize=(10.0, 8.0))
ax1 = fig.add_subplot(111)
ax1.set_title("test data accuracy")

ax1.plot(accuracy_stack)
ax1.set_xlabel("step")
plt.show()