In [1]:
import numpy as np

from ML2_lib import format_data
from ML2_lib import RV_SGD_Torch

In [2]:
X_train, y_train, X_test, y_test = format_data.MNIST_data().return_data()

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:62: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:67: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/U

In [18]:
hoge = RV_SGD_Torch.RVSGDByTorch(lr = 0.001)
model_list = hoge.learn(k=5, x=X_train, y=y_train,model_type="FF_L1")

In [19]:
model_list

[FF_L1(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L1(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L1(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L1(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L1(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 )]

In [20]:
selected = hoge.valid(model_candidates=model_list,k=5,valid_x=X_test,valid_y=y_test)

[108.44144439697266, 109.7315902709961, 84.83683776855469, 74.83685302734375, 68.34386444091797]
[96.45659637451172, 99.00220489501953, 69.05790710449219, 53.41676330566406, 47.37433624267578]
[94.83191680908203, 109.91207885742188, 84.6991958618164, 66.40987396240234, 62.43042755126953]
[104.50121307373047, 101.82775115966797, 74.17781829833984, 59.13737106323242, 63.975929260253906]
[108.04930877685547, 108.9394302368164, 82.36002349853516, 47.3016242980957, 49.361297607421875]
[108.44144439697266, 96.45659637451172, 94.83191680908203, 101.82775115966797, 108.04930877685547]
2


In [21]:
for i in range(5):
    hoge.prediction(x=X_test,y=y_test,model=model_list[i])

[[ 936    0    1    2    2   17   13    3    4    2]
 [   0 1045   26   31    0    5    2    0   23    3]
 [  33    9  867   17   14    7   25   13   40    7]
 [  19    5   33  824    5   56    4    3   37   24]
 [   5    4   11    2  831    1   30    2   10   86]
 [  40    1    5   46   16  701   17    6   51    9]
 [  22    1    5    2   21   13  887    1    6    0]
 [   8    9   45   30   14    5    3  801   19   94]
 [  32    7   24   35   17   23   16    2  782   36]
 [  22    3    4   14  108    6    2   15   24  811]]
              precision    recall  f1-score   support

           0       0.84      0.96      0.89       980
           1       0.96      0.92      0.94      1135
           2       0.85      0.84      0.84      1032
           3       0.82      0.82      0.82      1010
           4       0.81      0.85      0.83       982
           5       0.84      0.79      0.81       892
           6       0.89      0.93      0.91       958
           7       0.95      0.78   

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:82: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:82: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


[[ 856    0    5    2    2   63   42    1    6    3]
 [   0 1096    2   10    2    7    2    1   14    1]
 [  11   24  831   30   25   16   25   13   50    7]
 [   6    2   20  815    0   89    7   11   42   18]
 [   1    4   11    0  814   13   29    2   35   73]
 [  10    4    5   26    8  788   15    3   24    9]
 [   4    5    4    5   15   29  883    1   11    1]
 [   3   15   34    9   10   12    1  825   12  107]
 [   3   12    2   24    9   82   13    6  799   24]
 [   7    5    2    4   41   30    5   12   30  873]]
              precision    recall  f1-score   support

           0       0.95      0.87      0.91       980
           1       0.94      0.97      0.95      1135
           2       0.91      0.81      0.85      1032
           3       0.88      0.81      0.84      1010
           4       0.88      0.83      0.85       982
           5       0.70      0.88      0.78       892
           6       0.86      0.92      0.89       958
           7       0.94      0.80   

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:82: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:82: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


[[ 833    0    6    8    1  101    8    2   15    6]
 [   0 1035    3   14    0   15    4    1   62    1]
 [  11    8  840   31   11   19   18   11   72   11]
 [   5    2   21  801    0  102    4    7   52   16]
 [   3    4    7    6  778   15   13    4   55   97]
 [   4    0    7   24    2  805    9    1   35    5]
 [  10    4   24    0   14   56  811    3   31    5]
 [   1    9   38   21    9   15    0  814   23   98]
 [   2    5   12   18    7   43    6    5  869    7]
 [   1    6   12   13   26   33    2   14   45  857]]
              precision    recall  f1-score   support

           0       0.96      0.85      0.90       980
           1       0.96      0.91      0.94      1135
           2       0.87      0.81      0.84      1032
           3       0.86      0.79      0.82      1010
           4       0.92      0.79      0.85       982
           5       0.67      0.90      0.77       892
           6       0.93      0.85      0.88       958
           7       0.94      0.79   

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:82: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


In [22]:

hoge.prediction(x=X_test,y=y_test,model=selected)

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:82: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


[[ 933    0    9    4    2    4   18    2    7    1]
 [   0 1005   11   18    3    2   11    2   82    1]
 [  10    8  856   30   19    1   33   16   55    4]
 [  13    1   36  862    2    4    4   14   64   10]
 [   1    0    3    5  842    1   35    4   32   59]
 [  31    1   19   77   16  554   44   16  120   14]
 [  15    2   22    1   26    7  876    0    8    1]
 [   4    8   19   19   16    2    1  892   26   41]
 [  13    3   15   25    7    8   23    8  866    6]
 [  10    3    1   17   55    3    5   36   28  851]]
              precision    recall  f1-score   support

           0       0.91      0.95      0.93       980
           1       0.97      0.89      0.93      1135
           2       0.86      0.83      0.85      1032
           3       0.81      0.85      0.83      1010
           4       0.85      0.86      0.85       982
           5       0.95      0.62      0.75       892
           6       0.83      0.91      0.87       958
           7       0.90      0.87   

(tensor(83.6567), 0.8537)