In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import torch
from tqdm.notebook import tqdm

from ML2_lib import RV_SGDAve


import torch
import torch.nn.functional as F
import torch.optim as optim

from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
from sklearn import model_selection
from ML2_lib import models

In [2]:
from torch.optim.swa_utils import AveragedModel, SWALR
from torch.optim.lr_scheduler import CosineAnnealingLR


hoge = RV_SGDAve.RVSGDByTorch(lr=1)


In [3]:
real_data = load_iris()
x = real_data.data

scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)
# x = x.T


In [4]:
y = real_data.target
y = y.T

data_train, data_test, label_train, label_test = model_selection.train_test_split(x, y)

model = models.LinearClassification(4,3)
lppl = hoge.learn(k=3,x=data_train,y=label_train,model=model)

In [15]:
from torch.optim.swa_utils import AveragedModel, SWALR
from torch.optim.lr_scheduler import CosineAnnealingLR


model = models.LinearClassification(4,3)
optimizer = optim.SGD(model.parameters(), lr=0.1)
swa_model = AveragedModel(model)
scheduler = CosineAnnealingLR(optimizer, T_max=150)
swa_start = 5

train_X = torch.Tensor(real_data.data).float()## torch.Tensor型: Pytorch版のnumpy形式
train_y = torch.LongTensor(real_data.target)

for epoch in range(150):
      optimizer.zero_grad()

      output = model(train_X)
      loss = F.nll_loss(output, train_y)
      loss.backward()

      optimizer.step()
      prediction = output.data.max(1)[1]
      print(model.state_dict()['fc1.weight'])
      if epoch > swa_start:
          swa_model.update_parameters(model)
# # Use swa_model to make predictions on test data
preds = swa_model(train_X)



tensor([[-0.2897,  0.3854,  0.2863,  0.3112],
        [ 0.0746,  0.2814, -0.0487, -0.5024],
        [ 0.5552,  0.1047, -0.3040, -0.2229]])
tensor([[-0.2714,  0.4277,  0.2227,  0.2807],
        [ 0.2233,  0.3467,  0.0646, -0.4669],
        [ 0.3884, -0.0028, -0.3537, -0.2280]])
tensor([[-0.2719,  0.4593,  0.1497,  0.2475],
        [ 0.1172,  0.2792,  0.0142, -0.4830],
        [ 0.4949,  0.0331, -0.2304, -0.1786]])
tensor([[-0.2271,  0.5120,  0.1117,  0.2263],
        [ 0.2162,  0.3182,  0.0961, -0.4574],
        [ 0.3511, -0.0587, -0.2742, -0.1831]])
tensor([[-0.2258,  0.5415,  0.0468,  0.1967],
        [ 0.1019,  0.2477,  0.0376, -0.4765],
        [ 0.4641, -0.0176, -0.1509, -0.1343]])
tensor([[-0.1837,  0.5899,  0.0136,  0.1780],
        [ 0.2092,  0.2909,  0.1253, -0.4490],
        [ 0.3147, -0.1092, -0.2054, -0.1432]])
tensor([[-0.1905,  0.6120, -0.0493,  0.1499],
        [ 0.0944,  0.2216,  0.0629, -0.4699],
        [ 0.4363, -0.0621, -0.0801, -0.0942]])
tensor([[-0.1488,  0.6571, 

In [12]:
swa_model.state_dict()

OrderedDict([('n_averaged', tensor(144)),
             ('module.fc1.weight',
              tensor([[-0.1626,  1.0063, -0.6157, -0.4264],
                      [ 0.1138, -0.5695,  0.1814,  0.1841],
                      [-0.5724, -0.5873,  0.9872,  0.8668]])),
             ('module.fc1.bias', tensor([ 0.0649,  0.4475, -0.0016]))])