In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from ML2_lib import models
from ML2_lib import SGDByTorch
import torch.nn.functional as F
import torch
from sklearn.preprocessing import LabelBinarizer
from ML2_lib import format_data

In [2]:
name_path = "data/adult/adult_classification.names"
train_path = "data/adult/adult_classification.csv"
test_path = "data/adult/adult_classification.test"
hoge = format_data.Format(train_path=train_path,name_path=name_path,test_path=test_path)

In [3]:
X_train, y_train, X_test, y_test = hoge.data_return()

the number of data/adult/adult_classification.csv records:32561

missing value info:
age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
label                0
dtype: int64

the number of data/adult/adult_classification.csv records after trimming:30162

the number of data/adult/adult_classification.test records:16281

missing value info:
age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
label               0
dtype: int64

the number of data/adult/adult_classification.

In [4]:
w_dim = X_train.shape[1]
class_num = int(max(y_train) + 1)
unit_num = 5
model = models.LinearClassification(w_num=w_dim,c_num=class_num)

In [5]:
hoge = SGDByTorch.SGDTorch(lr=0.1)

In [6]:
sgd_model, stack, loss_stack, test_loss_stack,accuracy_stack = hoge.learn(x=X_train, y=y_train, model=model,class_num=class_num,X_test=X_test,Y_test=y_test)

1
2
step : 0
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
step : 10
[[    0 11360]
 [    0  3700]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00     11360
           1       0.25      1.00      0.39      3700

    accuracy                           0.25     15060
   macro avg       0.12      0.50      0.20     15060
weighted avg       0.06      0.25      0.10     15060

正解率 : 0.2456839309428951
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
step : 20
[[9594 1766]
 [1692 2008]]
              precision    recall  f1-score   support

           0       0.85      0.84      

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/

1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
step : 30
[[11357     3]
 [ 3695     5]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.62      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.69      0.50      0.43     15060
weighted avg       0.72      0.75      0.65     15060

正解率 : 0.7544488711819389
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
step : 40
[[11360     0]
 [ 3700     0]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86     11360
           1       0.00      0.00      0.00      3700

    accuracy                           0.75     15060
   macro avg       0.38      0.50      0.43     15060
weighted avg       0.57      0.75      0.65     15060

正解率 : 0.7543160690571049
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
step : 50


/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[11126   234]
 [ 3236   464]]
              precision    recall  f1-score   support

           0       0.77      0.98      0.87     11360
           1       0.66      0.13      0.21      3700

    accuracy                           0.77     15060
   macro avg       0.72      0.55      0.54     15060
weighted avg       0.75      0.77      0.70     15060

正解率 : 0.7695883134130146
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
step : 60
[[11090   270]
 [ 3198   502]]
              precision    recall  f1-score   support

           0       0.78      0.98      0.86     11360
           1       0.65      0.14      0.22      3700

    accuracy                           0.77     15060
   macro avg       0.71      0.56      0.54     15060
weighted avg       0.75      0.77      0.71     15060

正解率 : 0.7697211155378486
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
step : 70
[[10986   374]
 [ 3027   673]]
              precision    recall  f1-score   support

           0       0.78      0.97      0.87     

KeyboardInterrupt: 