In [1]:
import numpy as np

from ML2_lib import format_data
from ML2_lib import RV_SGD_Torch

In [2]:
X_train, y_train, X_test, y_test = format_data.MNIST_data().return_data()

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:62: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:67: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/U

In [3]:
hoge = RV_SGD_Torch.RVSGDByTorch(lr = 0.1)
model_list = hoge.learn(k=5, x=X_train, y=y_train,model_type="linear")

In [4]:
model_list

[LinearClassification(
   (fc1): Linear(in_features=784, out_features=10, bias=True)
 ),
 LinearClassification(
   (fc1): Linear(in_features=784, out_features=10, bias=True)
 ),
 LinearClassification(
   (fc1): Linear(in_features=784, out_features=10, bias=True)
 ),
 LinearClassification(
   (fc1): Linear(in_features=784, out_features=10, bias=True)
 ),
 LinearClassification(
   (fc1): Linear(in_features=784, out_features=10, bias=True)
 )]

In [5]:
selected = hoge.valid(model_candidates=model_list,k=5,valid_x=X_test,valid_y=y_test)

[2.9654154777526855, 3.0850141048431396, 2.418632984161377, 1.8567800521850586, 1.8651409149169922]
[2.363844871520996, 2.6188619136810303, 1.880303978919983, 1.7127183675765991, 1.5447534322738647]
[2.071988582611084, 2.1247150897979736, 1.7371656894683838, 1.4733234643936157, 1.1853609085083008]
[2.9915289878845215, 3.1473681926727295, 2.390923023223877, 1.7740559577941895, 1.7085728645324707]
[3.2043232917785645, 3.1549365520477295, 2.5720629692077637, 1.613629937171936, 1.6277743577957153]
[2.9654154777526855, 2.363844871520996, 2.071988582611084, 2.9915289878845215, 3.1549365520477295]
2


In [6]:
for i in range(5):
    hoge.prediction(x=X_test,y=y_test,model=model_list[i])

[[923   0   0   6   1  25  10   1  13   1]
 [  0 961   3  80   0  11   2   0  69   9]
 [ 31   6 725 129  11   5  18   9  77  21]
 [ 14   0   5 885   2  52   2   3  24  23]
 [  5   0   4   3 789   1   9   4  38 129]
 [ 20   1   5  57   7 667  17   3  92  23]
 [ 27   4  10   3  18  23 840   2  24   7]
 [  3   6  15  50   6   2   0 773  31 142]
 [ 11   2  11  76   8  20   8   1 791  46]
 [ 10   1   2  17  36   9   0  12  40 882]]
              precision    recall  f1-score   support

           0       0.88      0.94      0.91       980
           1       0.98      0.85      0.91      1135
           2       0.93      0.70      0.80      1032
           3       0.68      0.88      0.76      1010
           4       0.90      0.80      0.85       982
           5       0.82      0.75      0.78       892
           6       0.93      0.88      0.90       958
           7       0.96      0.75      0.84      1028
           8       0.66      0.81      0.73       974
           9       0.69     

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:82: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:82: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:82: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:82: UserWarning: To copy construct from a tensor, it is recommended to use sourceTe

In [7]:

hoge.prediction(x=X_test,y=y_test,model=selected)

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:82: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


[[ 942    0    5    5    1    3   16    2    6    0]
 [   0 1080    8    9    1    1    4    1   30    1]
 [   8    1  892   25   15    2   41    5   30   13]
 [   5    0   22  900    4   20    9   10   31    9]
 [   1    2    8    2  841    1   29    1   18   79]
 [  22   10   14   59   13  629   42    8   84   11]
 [  12    1    7    2   18    4  906    0    8    0]
 [   5   11   31   18   13    1    0  874   10   65]
 [  10   16   15   35   10   19   22    5  830   12]
 [  13    3    9   16   48    8    3   11   37  861]]
              precision    recall  f1-score   support

           0       0.93      0.96      0.94       980
           1       0.96      0.95      0.96      1135
           2       0.88      0.86      0.87      1032
           3       0.84      0.89      0.86      1010
           4       0.87      0.86      0.86       982
           5       0.91      0.71      0.80       892
           6       0.85      0.95      0.89       958
           7       0.95      0.85   

(tensor(1.7185), 0.8755)

In [11]:
from ML2_lib import valid
import numpy as np

In [12]:
valid.median_of_means(np.array([1,2,3,4,5]),n_blocks=3)

2.0