In [1]:
import numpy as np

from ML2_lib import format_data
from ML2_lib import RV_SGD_Torch

from sklearn.model_selection import train_test_split

from tqdm import tqdm_notebook

In [2]:
X_train, y_train, X_test, y_test = format_data.MNIST_data().return_data()
X_train, X_valid = train_test_split(X_train, test_size=0.1, shuffle=False)
y_train, y_valid = train_test_split(y_train, test_size=0.1, shuffle=False)

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:62: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:67: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/U

In [12]:
hoge = RV_SGD_Torch.RVSGDByTorch(lr=0.0002)
k_model_list = []
for i in tqdm_notebook(range(1, 10)):
    result_model = hoge.run_RVSGD(x_train=X_train, y_train=y_train, valid_x=X_valid, valid_y=y_valid, k=i,
                                  model_type="FF_L2")
    k_model_list.append(result_model)






<ipython-input-12-5c0c2a472d38>:3: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm_notebook(range(1, 10)):


  0%|          | 0/9 [00:00<?, ?it/s]

In [13]:
k_model_list

[FF_L2(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=512, bias=True)
   (fc3): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L2(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=512, bias=True)
   (fc3): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L2(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=512, bias=True)
   (fc3): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L2(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=512, bias=True)
   (fc3): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L2(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=512, bias=

In [14]:
for i in k_model_list:
    hoge.prediction(x=X_test, y=y_test, model=i, is_print=True)

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


[[ 954    0    7    2    1    4    7    2    3    0]
 [   0 1087   16    6    1    2    4    2   17    0]
 [   6    5  961   21    3    2    5    7   20    2]
 [   1    2   17  921    1   26    0    7   24   11]
 [   2    2    6    2  919    6    6    1    4   34]
 [   6    2    2   30    3  821    8    1   17    2]
 [  10    3    8    3   10   23  891    1    8    1]
 [   3    4   30   15   10    3    1  924    7   31]
 [   7    3   14   30   13   19    5    2  873    8]
 [   6    6    6   12   51   13    4   11   16  884]]
              precision    recall  f1-score   support

           0       0.96      0.97      0.97       980
           1       0.98      0.96      0.97      1135
           2       0.90      0.93      0.92      1032
           3       0.88      0.91      0.90      1010
           4       0.91      0.94      0.92       982
           5       0.89      0.92      0.91       892
           6       0.96      0.93      0.94       958
           7       0.96      0.90   

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


[[ 949    1    7    3    1    2   11    2    3    1]
 [   0 1105   11    2    1    1    2    8    4    1]
 [   8   11  933   22   18    0   10   13   15    2]
 [   1    0   14  926    1   22    4   16   19    7]
 [   1    3    7    2  907    0   14    9    6   33]
 [   7    2    6   51    6  752   13   17   28   10]
 [   6    4    8    1   13    7  907    3    8    1]
 [   3    9   17    4    5    0    1  970    4   15]
 [   5    6   10   60   14    6    9    9  840   15]
 [   8    3    1    9   61    2    1   65   12  847]]
              precision    recall  f1-score   support

           0       0.96      0.97      0.96       980
           1       0.97      0.97      0.97      1135
           2       0.92      0.90      0.91      1032
           3       0.86      0.92      0.89      1010
           4       0.88      0.92      0.90       982
           5       0.95      0.84      0.89       892
           6       0.93      0.95      0.94       958
           7       0.87      0.94   

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


[[ 911    0   13   12    2   17   12    0    4    9]
 [   0 1086    5    6    0    3    1    3   27    4]
 [   1    3  902   37    6    2    6   15   52    8]
 [   0    1   14  934    0   19    0    5   27   10]
 [   5    0    5   11  765    8   11    6   21  150]
 [   3    2    2   46    1  779   10    2   37   10]
 [   4    5    9    2    9   24  888    1    8    8]
 [   4    6   17   26    1    6    1  895   20   52]
 [   1    0   12   33    4   15    5    4  878   22]
 [   6    1    3   45   19   13    1   15   33  873]]
              precision    recall  f1-score   support

           0       0.97      0.93      0.95       980
           1       0.98      0.96      0.97      1135
           2       0.92      0.87      0.90      1032
           3       0.81      0.92      0.86      1010
           4       0.95      0.78      0.86       982
           5       0.88      0.87      0.88       892
           6       0.95      0.93      0.94       958
           7       0.95      0.87   

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


[[ 958    0    6    0    1    4    5    0    4    2]
 [   0 1093   15    1    4    5    5    5    7    0]
 [   9    7  933    7   18   12   10    8   26    2]
 [   2    9   49  814    3   66    1   16   41    9]
 [   1   10   16    0  893    2    2    3    8   47]
 [  20    0    7   27   10  795    8    2   14    9]
 [  23    3   25    3   31   20  846    2    5    0]
 [  10   12   52    5   12    9    1  883    8   36]
 [  13    4   25   15   13   46    7    4  838    9]
 [   5   10   10    7   71   15    1   24   37  829]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95       980
           1       0.95      0.96      0.96      1135
           2       0.82      0.90      0.86      1032
           3       0.93      0.81      0.86      1010
           4       0.85      0.91      0.88       982
           5       0.82      0.89      0.85       892
           6       0.95      0.88      0.92       958
           7       0.93      0.86   

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


In [15]:

col_name_list = []

lr_list = [0.1, 0.01, 0.001]
model_type_list = ["linear", "FF_L1", "FF_L2"]

for lr, model_type in zip(lr_list, model_type_list):
    for k in range(1, 10):
        col_name_list.append(f"RVSGD_model_{model_type}_lr_{lr}_k_{k}")

In [16]:
col_name_list

['RVSGD_model_linear_lr_0.1_k_1',
 'RVSGD_model_linear_lr_0.1_k_2',
 'RVSGD_model_linear_lr_0.1_k_3',
 'RVSGD_model_linear_lr_0.1_k_4',
 'RVSGD_model_linear_lr_0.1_k_5',
 'RVSGD_model_linear_lr_0.1_k_6',
 'RVSGD_model_linear_lr_0.1_k_7',
 'RVSGD_model_linear_lr_0.1_k_8',
 'RVSGD_model_linear_lr_0.1_k_9',
 'RVSGD_model_FF_L1_lr_0.01_k_1',
 'RVSGD_model_FF_L1_lr_0.01_k_2',
 'RVSGD_model_FF_L1_lr_0.01_k_3',
 'RVSGD_model_FF_L1_lr_0.01_k_4',
 'RVSGD_model_FF_L1_lr_0.01_k_5',
 'RVSGD_model_FF_L1_lr_0.01_k_6',
 'RVSGD_model_FF_L1_lr_0.01_k_7',
 'RVSGD_model_FF_L1_lr_0.01_k_8',
 'RVSGD_model_FF_L1_lr_0.01_k_9',
 'RVSGD_model_FF_L2_lr_0.001_k_1',
 'RVSGD_model_FF_L2_lr_0.001_k_2',
 'RVSGD_model_FF_L2_lr_0.001_k_3',
 'RVSGD_model_FF_L2_lr_0.001_k_4',
 'RVSGD_model_FF_L2_lr_0.001_k_5',
 'RVSGD_model_FF_L2_lr_0.001_k_6',
 'RVSGD_model_FF_L2_lr_0.001_k_7',
 'RVSGD_model_FF_L2_lr_0.001_k_8',
 'RVSGD_model_FF_L2_lr_0.001_k_9']

In [17]:
import datetime
import pandas as pd

n_trials = 10
X_train, y_train, X_test, y_test = format_data.MNIST_data().return_data()
X_train, X_valid = train_test_split(X_train, test_size=0.1, shuffle=False)
y_train, y_valid = train_test_split(y_train, test_size=0.1, shuffle=False)

lr = 0.002
model_type = "FF_L1"

result_loss = []
result_accuracy = []

col_name_list = []

for k in range(1, 10):
    col_name_list.append(f"k_{k}")

for i in tqdm_notebook(range(n_trials)):

    trial_result_loss = []
    trial_result_accuracy = []

    hoge = RV_SGD_Torch.RVSGDByTorch(lr=lr)
    k_model_list = []

    for k in range(1, 10):
        result_model = hoge.run_RVSGD(x_train=X_train, y_train=y_train, valid_x=X_valid, valid_y=y_valid, k=k,
                                      model_type=model_type)
        k_model_list.append(result_model)

    for i_model in k_model_list:
        test_loss, accuracy = hoge.prediction(x=X_test, y=y_test, model=i_model, is_print=False)
        trial_result_accuracy.append(accuracy)
        trial_result_loss.append(test_loss)

    result_loss.append(trial_result_loss)
    result_accuracy.append(trial_result_accuracy)

now = datetime.datetime.now().strftime('%Y年%m月%d日%H時%M分')

result_accuracy_pd = pd.DataFrame(np.array(result_accuracy), columns=col_name_list)

result_accuracy_pd.to_csv(f"RVSGD_MNIST_trial_{n_trials}_{now}_model_{model_type}.csv", index=False)

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:62: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:67: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:52: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:57: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")
<ipython-input-17-73c51f328d60>:20: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm_notebook(range(n_trials)):


  0%|          | 0/10 [00:00<?, ?it/s]

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


In [20]:
now.strftime('%Y年%m月%d日%H時%M分')

'2021年12月23日19時43分'