In [15]:
import numpy as np

from ML2_lib import format_data
from ML2_lib import RV_SGD_Torch

from sklearn.model_selection import train_test_split

from tqdm import tqdm_notebook

In [16]:
X_train, y_train, X_test, y_test = format_data.MNIST_data().return_data()
X_train, X_valid = train_test_split(X_train, test_size=0.1, shuffle=False)
y_train, y_valid = train_test_split(y_train, test_size=0.1, shuffle=False)

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:62: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:67: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:52: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:57: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


In [27]:
hoge = RV_SGD_Torch.RVSGDByTorch(lr=0.025)
k_model_list = []
for i in tqdm_notebook(range(1, 10)):
    result_model = hoge.run_RVSGD(x_train=X_train, y_train=y_train, valid_x=X_valid, valid_y=y_valid, k=i,
                                  model_type="FF_L1")
    k_model_list.append(result_model)






<ipython-input-27-3da21da01647>:3: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm_notebook(range(1,10)):


  0%|          | 0/9 [00:00<?, ?it/s]

In [28]:
k_model_list

[FF_L1(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L1(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L1(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L1(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L1(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L1(
   (fc1): Linear(in_features=784, out_features=512, bias=True)
   (fc2): Linear(in_features=512, out_features=10, bias=True)
   (relu): ReLU()
 ),
 FF_L1(
   (fc1): Linear(in_features=784, out_features=512, bias=True)

In [29]:
for i in k_model_list:
    hoge.prediction(x=X_test, y=y_test, model=i, is_print=True)

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


[[ 801    0    5    4    3   12    2   10  140    3]
 [   0 1024   14   21    3    0    2    9   60    2]
 [  22    3  848   14    3    2    7   28  104    1]
 [   0    1   16  806    2   34    1    8  138    4]
 [   3    2   10    4  751    3    7   13  146   43]
 [  14    2    3   36   10  687    5   12  119    4]
 [  17   13    2    8   32   38  708    2  135    3]
 [   5    7   17   14   10    3    1  868   74   29]
 [   7    5    9   24   10   42    7    6  863    1]
 [   7    2    6   13   52   21    3  118  221  566]]
              precision    recall  f1-score   support

           0       0.91      0.82      0.86       980
           1       0.97      0.90      0.93      1135
           2       0.91      0.82      0.86      1032
           3       0.85      0.80      0.82      1010
           4       0.86      0.76      0.81       982
           5       0.82      0.77      0.79       892
           6       0.95      0.74      0.83       958
           7       0.81      0.84   

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


[[ 896    1    9    1   13    6    9    3   40    2]
 [   6 1072    5    6    4    1    4    6   30    1]
 [  21    8  756   37   20   14    9   18  140    9]
 [   3    3   12  863    2   20    1    7   87   12]
 [   4    7   13    7  853    5   15    7   46   25]
 [  22    5    8   64   23  648   11   11   79   21]
 [  11    3   25    3   46   15  816    3   32    4]
 [   1    4   13   20   35    3    2  844   24   82]
 [  13    6   13   41   37   22   10    5  811   16]
 [   7    4    7   33  254   16    3   28   66  591]]
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       980
           1       0.96      0.94      0.95      1135
           2       0.88      0.73      0.80      1032
           3       0.80      0.85      0.83      1010
           4       0.66      0.87      0.75       982
           5       0.86      0.73      0.79       892
           6       0.93      0.85      0.89       958
           7       0.91      0.82   

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


[[ 909    0    8    4    4   29    8    2   16    0]
 [   0 1080    8    2    1    2    2    1   38    1]
 [  12    5  871   30   17   19    6   17   53    2]
 [   3    7   24  867    8   43    3   17   28   10]
 [   0    2    8    5  894    5    9    5   13   41]
 [   9    6    9   42   21  751    8    9   26   11]
 [  19    4    9    2   27   68  808    3   17    1]
 [   2   12   24    8   50    7    1  858   15   51]
 [   7    4   15   14   68   70   16    3  767   10]
 [   5    5    9   21  228   25    4   22   22  668]]
              precision    recall  f1-score   support

           0       0.94      0.93      0.93       980
           1       0.96      0.95      0.96      1135
           2       0.88      0.84      0.86      1032
           3       0.87      0.86      0.86      1010
           4       0.68      0.91      0.78       982
           5       0.74      0.84      0.79       892
           6       0.93      0.84      0.89       958
           7       0.92      0.83   

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


[[ 932    1    7    3    6    5   15    5    6    0]
 [  14 1045   19   12    5    1   11   15   13    0]
 [  18    0  925   12   17    2   23   15   13    7]
 [   4    5  107  776    6   42    6   14   36   14]
 [   2    1   11    2  885    4   12   12    8   45]
 [  24    5   13   26   17  709   35   25   22   16]
 [  11    2   18    3   12   10  897    2    3    0]
 [   2    2   48   16   16    1    2  921    6   14]
 [  50    8  130   33   46   41   22   28  588   28]
 [  11    4    3   19  114   10    6   64   30  748]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91       980
           1       0.97      0.92      0.95      1135
           2       0.72      0.90      0.80      1032
           3       0.86      0.77      0.81      1010
           4       0.79      0.90      0.84       982
           5       0.86      0.79      0.83       892
           6       0.87      0.94      0.90       958
           7       0.84      0.90   

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())


In [30]:

col_name_list = []

lr_list = [0.1, 0.01, 0.001]
model_type_list = ["linear", "FF_L1", "FF_L2"]

for lr, model_type in zip(lr_list, model_type_list):
    for k in range(1, 10):
        col_name_list.append(f"RVSGD_model_{model_type}_lr_{lr}_k_{k}")

In [31]:
col_name_list

['RVSGD_model_linear_lr_0.1_k_1',
 'RVSGD_model_linear_lr_0.1_k_2',
 'RVSGD_model_linear_lr_0.1_k_3',
 'RVSGD_model_linear_lr_0.1_k_4',
 'RVSGD_model_linear_lr_0.1_k_5',
 'RVSGD_model_linear_lr_0.1_k_6',
 'RVSGD_model_linear_lr_0.1_k_7',
 'RVSGD_model_linear_lr_0.1_k_8',
 'RVSGD_model_linear_lr_0.1_k_9',
 'RVSGD_model_FF_L1_lr_0.01_k_1',
 'RVSGD_model_FF_L1_lr_0.01_k_2',
 'RVSGD_model_FF_L1_lr_0.01_k_3',
 'RVSGD_model_FF_L1_lr_0.01_k_4',
 'RVSGD_model_FF_L1_lr_0.01_k_5',
 'RVSGD_model_FF_L1_lr_0.01_k_6',
 'RVSGD_model_FF_L1_lr_0.01_k_7',
 'RVSGD_model_FF_L1_lr_0.01_k_8',
 'RVSGD_model_FF_L1_lr_0.01_k_9',
 'RVSGD_model_FF_L2_lr_0.001_k_1',
 'RVSGD_model_FF_L2_lr_0.001_k_2',
 'RVSGD_model_FF_L2_lr_0.001_k_3',
 'RVSGD_model_FF_L2_lr_0.001_k_4',
 'RVSGD_model_FF_L2_lr_0.001_k_5',
 'RVSGD_model_FF_L2_lr_0.001_k_6',
 'RVSGD_model_FF_L2_lr_0.001_k_7',
 'RVSGD_model_FF_L2_lr_0.001_k_8',
 'RVSGD_model_FF_L2_lr_0.001_k_9']

In [40]:
import datetime
import pandas as pd

n_trials = 2
X_train, y_train, X_test, y_test = format_data.MNIST_data().return_data()
X_train, X_valid = train_test_split(X_train, test_size=0.1, shuffle=False)
y_train, y_valid = train_test_split(y_train, test_size=0.1, shuffle=False)

lr = 0.025
model_type = "FF_L1"

result_loss = []
result_accuracy = []

col_name_list = []

for k in range(1, 2):
    col_name_list.append(f"k_{k}")

for i in tqdm_notebook(range(n_trials)):

    trial_result_loss = []
    trial_result_accuracy = []

    hoge = RV_SGD_Torch.RVSGDByTorch(lr=lr)
    k_model_list = []

    for k in range(1, 2):
        result_model = hoge.run_RVSGD(x_train=X_train, y_train=y_train, valid_x=X_valid, valid_y=y_valid, k=k,
                                      model_type=model_type)
        k_model_list.append(result_model)

    for i_model in k_model_list:
        test_loss, accuracy = hoge.prediction(x=X_test, y=y_test, model=i_model, is_print=False)
        trial_result_accuracy.append(accuracy)
        trial_result_loss.append(test_loss)

    result_loss.append(trial_result_loss)
    result_accuracy.append(trial_result_accuracy)

now = datetime.datetime.now()

result_accuracy_pd = pd.DataFrame(np.array(result_accuracy), columns=col_name_list)

result_accuracy_pd.to_csv(f"RVSGD_MNIST_trial_{n_trials}_{now}_model_FF_L1.csv", index=False)

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:62: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:67: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:52: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:57: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")
<ipython-input-40-55c249ab4427>:20: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm_notebook(range(n_trials)):


  0%|          | 0/2 [00:00<?, ?it/s]

/Users/naoki/ML2/GD/ML2_lib/RV_SGD_Torch.py:88: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = model(torch.tensor(x).float())
