In [9]:
from torchvision.datasets import MNIST
import optuna

mnist_data = MNIST('data/MNIST',download=False,)

In [10]:

mnist_data.train_data

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:62: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")


tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        ...,

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0,

In [11]:

mnist_data.train_labels

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:52: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


tensor([5, 0, 4,  ..., 5, 6, 8])

In [12]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from ML2_lib import models
from ML2_lib import SGDByTorch
import torch.nn.functional as F
import torch
from sklearn.preprocessing import LabelBinarizer
from ML2_lib import format_data



In [13]:

X_train = mnist_data.train_data.reshape(-1,784)
X_test = mnist_data.test_data.reshape(-1,784)
y_train = mnist_data.train_labels
y_test = mnist_data.test_labels

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:67: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:57: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


In [14]:
w_dim = X_train.shape[1]
class_num = int(max(y_train) + 1)
unit_num = 3
model = models.LinearClassification(w_num=w_dim,c_num=class_num)
model.parameter_init()

In [15]:
hoge = SGDByTorch.SGDTorchCheck(lr=0.1)

In [16]:
sgd_model, loss_stack, test_loss_stack,accuracy_stack = hoge.learn(x=X_train, y=y_train, model=model,class_num=class_num,X_test=X_test,Y_test=y_test)

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:114: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x).float()
/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:146: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


step : 0
OrderedDict([('fc1.weight', tensor([[ 2.4402,  2.8421, -2.9758,  ...,  3.6914,  3.9722,  2.1049],
        [ 4.1362,  3.3909,  1.5667,  ..., -2.3789,  3.1523,  4.7185],
        [-3.8923,  4.3601,  0.0909,  ...,  4.8018,  3.7035,  1.4217],
        ...,
        [ 2.0312,  2.4968,  4.1081,  ..., -3.1753,  2.0090,  1.1899],
        [ 3.4057,  3.9673, -2.6706,  ..., -2.2297, -2.5674, -2.8378],
        [ 3.1741,  1.0887,  4.0196,  ..., -1.3685, -3.8843,  4.2623]])), ('fc1.bias', tensor([-0.1000,  0.0000,  0.0000,  0.0000,  0.0000,  0.1000,  0.0000,  0.0000,
         0.0000,  0.0000]))])
[[  49  113  116 1944 2705  244  177  539    2   34]
 [1033  150  333   80   30 3942  519  577    2   76]
 [ 668 1268  353 1399  367  639  657  395   35  177]
 [ 173  225 1074 1301  279  597 2091  229    7  155]
 [ 278   73   11 1726  924  195 1192  533   17  893]
 [ 302  202  419 1116  392  808 1883  238    1   60]
 [ 828  858  171  671  682  369  288 1075    4  972]
 [ 370   49  324 2368  181  987  

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:146: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


step : 1000
OrderedDict([('fc1.weight', tensor([[ 2.4402,  2.8421, -2.9758,  ...,  3.6914,  3.9722,  2.1049],
        [ 4.1362,  3.3909,  1.5667,  ..., -2.3789,  3.1523,  4.7185],
        [-3.8923,  4.3601,  0.0909,  ...,  4.8018,  3.7035,  1.4217],
        ...,
        [ 2.0312,  2.4968,  4.1081,  ..., -3.1753,  2.0090,  1.1899],
        [ 3.4057,  3.9673, -2.6706,  ..., -2.2297, -2.5674, -2.8378],
        [ 3.1741,  1.0887,  4.0196,  ..., -1.3685, -3.8843,  4.2623]])), ('fc1.bias', tensor([-0.7000,  0.9000, -0.2000, -0.4000,  0.7000, -0.1000, -0.4000,  0.8000,
        -0.4000, -0.3000]))])
[[4086    2   42  926   76  188  294  174   22  113]
 [   3 5863   53  245    8   44  112  234   79  101]
 [ 101  392 2649 1352  149   23  556  429  177  130]
 [  45   80   65 5384   16  129   40  240   36   96]
 [  12   32   17  210 3925   18  298  218   35 1077]
 [ 204  195   22 2320  238 1333  381  230  133  365]
 [ 117  153  104  138  166   75 4878  128   17  142]
 [  45   58   16  157  131   3

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:146: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


step : 2000
OrderedDict([('fc1.weight', tensor([[ 2.4402,  2.8421, -2.9758,  ...,  3.6914,  3.9722,  2.1049],
        [ 4.1362,  3.3909,  1.5667,  ..., -2.3789,  3.1523,  4.7185],
        [-3.8923,  4.3601,  0.0909,  ...,  4.8018,  3.7035,  1.4217],
        ...,
        [ 2.0312,  2.4968,  4.1081,  ..., -3.1753,  2.0090,  1.1899],
        [ 3.4057,  3.9673, -2.6706,  ..., -2.2297, -2.5674, -2.8378],
        [ 3.1741,  1.0887,  4.0196,  ..., -1.3685, -3.8843,  4.2623]])), ('fc1.bias', tensor([-0.7000,  0.8924,  0.3000, -1.0001,  1.1021,  0.5000, -0.6000,  0.7000,
        -0.6860, -0.7000]))])
[[5371    0   44   85   29  185   58   15  114   22]
 [   5 5506  298  176    8  400   44   15  224   66]
 [  83   54 4937  209   88   63  104  102  280   38]
 [ 117   64  224 4237   26  990   27  183  182   81]
 [  28   27  111   17 4530  158   60   76  315  520]
 [ 244   51   68  392  137 3896  190   37  302  104]
 [ 182   45  355   24  147  342 4704   10   73   36]
 [  76   80  148   63  121   8

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:146: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


step : 3000
OrderedDict([('fc1.weight', tensor([[ 2.4402,  2.8421, -2.9758,  ...,  3.6914,  3.9722,  2.1049],
        [ 4.1362,  3.3909,  1.5667,  ..., -2.3789,  3.1523,  4.7185],
        [-3.8923,  4.3601,  0.0909,  ...,  4.8018,  3.7035,  1.4217],
        ...,
        [ 2.0312,  2.4968,  4.1081,  ..., -3.1753,  2.0090,  1.1899],
        [ 3.4057,  3.9673, -2.6706,  ..., -2.2297, -2.5674, -2.8378],
        [ 3.1741,  1.0887,  4.0196,  ..., -1.3685, -3.8843,  4.2623]])), ('fc1.bias', tensor([-1.1000,  1.0924,  0.3000, -1.1002,  1.3021,  0.6000, -0.6000,  0.8000,
        -0.9860, -0.5000]))])
[[4041    1  250  153   90  170   59   14  938  207]
 [   1 5745  171  152   11   20   29    4  541   68]
 [  18   62 4964  152  107    6   65   48  461   75]
 [  23   63  282 4724   35  133   25   53  615  178]
 [   3   17   97   25 4654    6   31   20  199  790]
 [  57   56  104  605  262 2324  152   18 1456  387]
 [  66   58  390   27  270  136 4619    3  257   92]
 [  18   71  155  136  193   1

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:146: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


KeyboardInterrupt: 

In [ ]:


fig = plt.figure(figsize=(10.0, 8.0))
ax1 = fig.add_subplot(111)

ax1.set_title("train data NLL Loss")

ax1.plot(loss_stack)
ax1.set_xlabel("step")
plt.show()

In [ ]:
fig = plt.figure(figsize=(10.0, 8.0))
ax1 = fig.add_subplot(111)
ax1.set_title("test data NLL Loss")

ax1.plot(test_loss_stack)
ax1.set_xlabel("step")
plt.show()

In [ ]:
fig = plt.figure(figsize=(10.0, 8.0))
ax1 = fig.add_subplot(111)
ax1.set_title("test data accuracy")

ax1.plot(accuracy_stack)
ax1.set_xlabel("step")
plt.show()

In [ ]:

accuracy_stack
