In [1]:
from torchvision.datasets import MNIST
import optuna

mnist_data = MNIST('data/MNIST',download=True,)

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [2]:

mnist_data.train_data

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:62: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")


tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        ...,

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0,

In [3]:

mnist_data.train_labels

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:52: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


tensor([5, 0, 4,  ..., 5, 6, 8])

In [4]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from ML2_lib import models
from ML2_lib import SGDByTorch
import torch.nn.functional as F
import torch
from sklearn.preprocessing import LabelBinarizer
from ML2_lib import format_data

In [5]:
name_path = "data/adult/adult_classification.names"
train_path = "data/adult/adult_classification.csv"
test_path = "data/adult/adult_classification.test"

In [6]:

X_train = mnist_data.train_data.reshape(-1,784)
X_test = mnist_data.test_data.reshape(-1,784)
y_train = mnist_data.train_labels
y_test = mnist_data.test_labels

/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:62: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:67: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:52: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
/Users/naoki/.pyenv/versions/ML2/lib/python3.8/site-packages/torchvision/datasets/mnist.py:57: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


In [10]:
w_dim = X_train.shape[1]
class_num = int(max(y_train) + 1)
unit_num = 3
model = models.LinearClassification(w_num=w_dim,c_num=class_num)
model.parameter_init()

In [11]:
hoge = SGDByTorch.SGDTorchCheck(lr=0.001)

In [ ]:
sgd_model, loss_stack, test_loss_stack,accuracy_stack = hoge.learn(x=X_train, y=y_train, model=model,class_num=class_num,X_test=X_test,Y_test=y_test)

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:103: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x).float()
/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:135: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


step : 0
OrderedDict([('fc1.weight', tensor([[-0.1504, -0.0060, -4.4531,  ...,  2.3889,  1.6819,  0.3525],
        [-3.3188, -0.4711,  3.5692,  ...,  4.6080,  2.0190,  1.4397],
        [ 4.6700, -2.5355, -3.6030,  ..., -3.2431,  3.7220, -1.3104],
        ...,
        [-0.8333,  4.5004, -3.3021,  ..., -2.9220, -4.4829,  2.2170],
        [-0.4725,  2.1637, -0.6565,  ..., -2.2385,  0.7619, -0.3093],
        [ 4.2147, -1.2455, -0.6154,  ..., -4.4324,  1.5115, -2.5477]])), ('fc1.bias', tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0010,  0.0000, -0.0010,
         0.0000,  0.0000]))])
[[ 427    0    1   20 1472 2941   84    2  851  125]
 [ 470    0 1635  209 1195 2826    0   50    1  356]
 [1226    1  205  122 1944 2040   24    9  136  251]
 [ 875    6  219   58 1059 3203   51    5  159  496]
 [1467   20  196  652 1203  677   86   29  272 1240]
 [1179    8   86  241  629 2000  325    4  276  673]
 [ 818   31  375  100  935 3122  250   14   99  174]
 [3019    4  303 1017  653  216  

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:135: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


step : 1000
OrderedDict([('fc1.weight', tensor([[-0.1504, -0.0060, -4.4531,  ...,  2.3889,  1.6819,  0.3525],
        [-3.3188, -0.4711,  3.5692,  ...,  4.6080,  2.0190,  1.4397],
        [ 4.6700, -2.5355, -3.6030,  ..., -3.2431,  3.7220, -1.3104],
        ...,
        [-0.8333,  4.5004, -3.3021,  ..., -2.9220, -4.4829,  2.2170],
        [-0.4725,  2.1637, -0.6565,  ..., -2.2385,  0.7619, -0.3093],
        [ 4.2147, -1.2455, -0.6154,  ..., -4.4324,  1.5115, -2.5477]])), ('fc1.bias', tensor([-8.0000e-03,  1.1000e-02, -3.0000e-03, -5.0000e-03, -4.8894e-09,
         4.0000e-03,  2.0000e-03,  9.0052e-03, -9.0052e-03, -1.0000e-03]))])
[[5298    3   47   50    7  108   36  249  108   17]
 [   1 5941   49    9    2   27    3  416  292    2]
 [ 108  224 4435  217   28   18  244  408  251   25]
 [  88   96  361 3967    8  682   15  519  370   25]
 [  42  160  155   49 3364   93  155  571   86 1167]
 [ 292   81  106  368  100 3050  177  268  855  124]
 [ 124  115  141   17  150  148 5006   97  

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:135: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


step : 2000
OrderedDict([('fc1.weight', tensor([[-0.1504, -0.0060, -4.4531,  ...,  2.3889,  1.6819,  0.3525],
        [-3.3188, -0.4711,  3.5692,  ...,  4.6080,  2.0190,  1.4397],
        [ 4.6700, -2.5355, -3.6030,  ..., -3.2431,  3.7220, -1.3104],
        ...,
        [-0.8333,  4.5004, -3.3021,  ..., -2.9220, -4.4829,  2.2170],
        [-0.4725,  2.1637, -0.6565,  ..., -2.2385,  0.7619, -0.3093],
        [ 4.2147, -1.2455, -0.6154,  ..., -4.4324,  1.5115, -2.5477]])), ('fc1.bias', tensor([-9.1754e-03,  1.1000e-02, -1.8246e-03, -3.0000e-03, -4.8894e-09,
         8.0000e-03,  3.0000e-03,  6.0052e-03, -1.4005e-02, -2.3283e-10]))])
[[5023    0   45  240    1  383  193    4   25    9]
 [   1 5752   92  136    2  138  195   12  411    3]
 [  43   17 5096  227   20   41  314   22  151   27]
 [   6   12  345 5085    3  477   52   29  111   11]
 [  38   40  201  194 3340  441  593    7  278  710]
 [  73   27   73  398   43 4196  365   10  189   47]
 [  26    8  112   23   17   87 5615    3  

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:135: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


step : 3000
OrderedDict([('fc1.weight', tensor([[-0.1504, -0.0060, -4.4531,  ...,  2.3889,  1.6819,  0.3525],
        [-3.3188, -0.4711,  3.5692,  ...,  4.6080,  2.0190,  1.4397],
        [ 4.6700, -2.5355, -3.6030,  ..., -3.2431,  3.7220, -1.3104],
        ...,
        [-0.8333,  4.5004, -3.3021,  ..., -2.9220, -4.4829,  2.2170],
        [-0.4725,  2.1637, -0.6565,  ..., -2.2385,  0.7619, -0.3093],
        [ 4.2147, -1.2455, -0.6154,  ..., -4.4324,  1.5115, -2.5477]])), ('fc1.bias', tensor([-0.0092,  0.0120, -0.0028, -0.0060, -0.0010,  0.0120,  0.0030,  0.0080,
        -0.0180,  0.0020]))])
[[5540    0   12   88    2  102   58    1   47   73]
 [   0 6009   39  112    2   66   38  213  234   29]
 [ 104   39 4484  301   78   40  379  134  242  157]
 [  58   12  133 5241    3  274   44  124  110  132]
 [  57   28    9   46 4052   51  186   38  132 1243]
 [ 192   30    9  388   36 3856  213   39  445  213]
 [ 103   19   29   16   28   75 5506    7  101   34]
 [  63   18   74  175   26   2

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:135: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


step : 4000
OrderedDict([('fc1.weight', tensor([[-0.1504, -0.0060, -4.4531,  ...,  2.3889,  1.6819,  0.3525],
        [-3.3188, -0.4711,  3.5692,  ...,  4.6080,  2.0190,  1.4397],
        [ 4.6700, -2.5355, -3.6030,  ..., -3.2431,  3.7220, -1.3104],
        ...,
        [-0.8333,  4.5004, -3.3021,  ..., -2.9220, -4.4829,  2.2170],
        [-0.4725,  2.1637, -0.6565,  ..., -2.2385,  0.7619, -0.3093],
        [ 4.2147, -1.2455, -0.6154,  ..., -4.4324,  1.5115, -2.5477]])), ('fc1.bias', tensor([-0.0102,  0.0140, -0.0018, -0.0060, -0.0010,  0.0150,  0.0020,  0.0090,
        -0.0220,  0.0010]))])
[[5530    0   74   32   10  104   46    3   56   68]
 [   2 6444   72    5    2   51    2    8  121   35]
 [  29   80 5093   76   78   44  123   99  216  120]
 [  37   57  386 4519    4  517   31   51  287  242]
 [  18   42   31    1 4730   47   84   16  112  761]
 [ 165   33   83  133   53 4256   83    6  389  220]
 [  54   37  158    2  115  138 5240    6  158   10]
 [  56   74  141   50   55   3

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:135: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


step : 5000
OrderedDict([('fc1.weight', tensor([[-0.1504, -0.0060, -4.4531,  ...,  2.3889,  1.6819,  0.3525],
        [-3.3188, -0.4711,  3.5692,  ...,  4.6080,  2.0190,  1.4397],
        [ 4.6700, -2.5355, -3.6030,  ..., -3.2431,  3.7220, -1.3104],
        ...,
        [-0.8333,  4.5004, -3.3021,  ..., -2.9220, -4.4829,  2.2170],
        [-0.4725,  2.1637, -0.6565,  ..., -2.2385,  0.7619, -0.3093],
        [ 4.2147, -1.2455, -0.6154,  ..., -4.4324,  1.5115, -2.5477]])), ('fc1.bias', tensor([-1.2176e-02,  1.5000e-02,  1.7543e-04, -4.0104e-03,  1.0381e-05,
         2.0000e-02,  2.0002e-03,  1.0005e-02, -2.9005e-02, -2.0000e-03]))])
[[5129    0  204  204   11  226   75   27   35   12]
 [   1 6487   67   99    3   31    4   28   20    2]
 [  14  104 4887  570   69   30   84   84  103   13]
 [   4   38  242 5601    5   91   17   54   44   35]
 [   9   99  113   49 4968   69  115   46   97  277]
 [ 103   50  256  738   59 3754  156   49  203   53]
 [  34   44  364   14   41   71 5325    2  

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:135: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


step : 6000
OrderedDict([('fc1.weight', tensor([[-0.1504, -0.0060, -4.4531,  ...,  2.3889,  1.6819,  0.3525],
        [-3.3188, -0.4711,  3.5692,  ...,  4.6080,  2.0190,  1.4397],
        [ 4.6700, -2.5355, -3.6030,  ..., -3.2431,  3.7220, -1.3104],
        ...,
        [-0.8333,  4.5004, -3.3021,  ..., -2.9220, -4.4829,  2.2170],
        [-0.4725,  2.1637, -0.6565,  ..., -2.2385,  0.7619, -0.3093],
        [ 4.2147, -1.2455, -0.6154,  ..., -4.4324,  1.5115, -2.5477]])), ('fc1.bias', tensor([-1.2131e-02,  1.3000e-02, -2.8246e-03, -5.0104e-03,  1.0385e-05,
         2.7580e-02,  2.0002e-03,  1.2005e-02, -3.4005e-02, -6.2452e-04]))])
[[5139    4   12   53    6  463  137   26   66   17]
 [   2 6487   12   69    5   65   14   12   76    0]
 [  37  179 3686  683   84   80  459  166  477  107]
 [  24   54   25 5345    5  346   50   89  132   61]
 [   4   77    2   21 4900  208  139   43   62  386]
 [  89   57    7  247   18 4544  164   29  219   47]
 [  25   35    8    8   49  148 5603    3  

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:135: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


step : 7000
OrderedDict([('fc1.weight', tensor([[-0.1504, -0.0060, -4.4531,  ...,  2.3889,  1.6819,  0.3525],
        [-3.3188, -0.4711,  3.5692,  ...,  4.6080,  2.0190,  1.4397],
        [ 4.6700, -2.5355, -3.6030,  ..., -3.2431,  3.7220, -1.3104],
        ...,
        [-0.8333,  4.5004, -3.3021,  ..., -2.9220, -4.4829,  2.2170],
        [-0.4725,  2.1637, -0.6565,  ..., -2.2385,  0.7619, -0.3093],
        [ 4.2147, -1.2455, -0.6154,  ..., -4.4324,  1.5115, -2.5477]])), ('fc1.bias', tensor([-1.4131e-02,  1.1000e-02, -8.2457e-04, -7.0104e-03,  1.0104e-03,
         3.1580e-02,  1.7858e-07,  1.3005e-02, -3.5005e-02,  3.7548e-04]))])
[[5730    0   38    2   10   42   24    9   65    3]
 [   2 5746  113   20    6   95   12   22  726    0]
 [  79    8 4976   82   78   45  167   85  421   17]
 [  68   17  314 3736    5  953   24   82  865   67]
 [  69   11   34    1 5129   45  119   34  244  156]
 [ 231    8   97   56   37 4443   91   27  400   31]
 [ 159    4  145    1   67   64 5350    0  

/Users/naoki/ML2/GD/ML2_lib/SGDByTorch.py:135: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_pred = self.model(torch.tensor(X_test).float())


In [ ]:


fig = plt.figure(figsize=(10.0, 8.0))
ax1 = fig.add_subplot(111)

ax1.set_title("train data NLL Loss")

ax1.plot(loss_stack)
ax1.set_xlabel("step")
plt.show()

In [ ]:
fig = plt.figure(figsize=(10.0, 8.0))
ax1 = fig.add_subplot(111)
ax1.set_title("test data NLL Loss")

ax1.plot(test_loss_stack)
ax1.set_xlabel("step")
plt.show()

In [ ]:
fig = plt.figure(figsize=(10.0, 8.0))
ax1 = fig.add_subplot(111)
ax1.set_title("test data accuracy")

ax1.plot(accuracy_stack)
ax1.set_xlabel("step")
plt.show()

In [ ]:

accuracy_stack
